apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: aakkiiff/current_weather_app_weather:36

        ports:
        - containerPort: 5000